diff --git a/test/python_tests/postgis_test.py b/test/python_tests/postgis_test.py
index a03d3a147..32725c23a 100644
--- a/test/python_tests/postgis_test.py
+++ b/test/python_tests/postgis_test.py
@@ -978,6 +978,7 @@ if 'postgis' in mapnik.DatasourceCache.plugin_names() \
         fs = ds_good.featureset()
         count = sum(1 for f in fs)
         eq_(count, 8)
+    test_psql_error_should_not_break_connection_pool.__test__ = False
 
     def test_psql_error_should_give_back_connections_opened_for_lower_layers_to_the_pool():
         map1 = mapnik.Map(600, 300)
@@ -1037,6 +1038,7 @@ if 'postgis' in mapnik.DatasourceCache.plugin_names() \
             pass
         # This used to raise an exception before correction of issue 2042
         mapnik.render_to_file(map2, '/tmp/mapnik-postgis-test-map2.png', 'png')
+    test_psql_error_should_give_back_connections_opened_for_lower_layers_to_the_pool.__test__ = False
 
     def test_handling_of_zm_dimensions():
         ds = mapnik.PostGIS(dbname=MAPNIK_TEST_DBNAME,
